### ISSUE TITLE
Version for .NET standard

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [thomasjo/highlight#6]
Hi, would you be interested in a PR for a .NET standard 2.0 version of your code?

I just worked on it for a Blazor project and it seems to be working.

Of course, I don't know all the ins and outs of the project, so more testing may be required.

I have just used the HtmlEngine to Highlight some HTML and C# strings.

Let me know if you are interested.

Thanks for the project - it has been a help to me - I appreciate it.

**Comment by servusDei2018** [comment]
Sounds great!

**Comment by thomasjo** [comment]
Thanks for the suggestion! Support for .NET Standard/Core was merged in #9.
